/* Copyright 2020-2021 The MathWorks, Inc. */
define({
    
        dialogTitle: 'MATLAB インストーラー',
        installButtonLabel: 'インストールの開始',
        downloadButtonLabel: 'ダウンロードの開始',
        forwardButtonLabel: '次へ',
        cancelButtonLabel: 'キャンセル',
        finishButtonLabel: '閉じる',
        guiltForwardButtonLabel: '学生である',
        closeLabel: 'OK',
        continueLabel: '続行',
        ignoreLabel: '無視',
        licenseAgreementTitle: 'MathWorks ライセンス許諾',
        patentsAndTrademarksTitle: '著作権、商標および特許',
        fikWorkflowLabel: 'ファイル インストール キーを使用したインストール',
        proxyTitle: 'プロキシ認証',
        proxyUser: 'プロキシ サーバーのユーザー ID:',
        proxyPassword: 'プロキシ サーバーのパスワード:',
        downloadOnlyWorkflowLabel: 'インストールせずにダウンロード',
        licenseManagerWorkflowLabel: 'ネットワーク ライセンス マネージャーのインストール',
        fikLabel: 'ファイル インストール キーの入力',
        fikContextHelp: 'ファイル インストール キーはインストールできる製品を特定し、インターネット接続なしでもインストールを行えるようにします。このワークフローではライセンス ファイルも必要です。ファイル インストール キーとライセンス ファイルのどちらも MathWorks ライセンス センターまたは担当のライセンス管理者から入手できます。',
        downloadFolderContextHelp: '製品を今すぐインストールせずにダウンロードして、後で 1 台以上のコンピューターにインストールできるようにします。',
        activationKeyContextHelp: 'アクティベーション キーは別のライセンスにリンクします。アクティベーション キーはライセンス管理者から入手できます。',
        proxyContextHelp: 'ご使用のマシンは、インターネット アクセスにプロキシ サーバーを使用するように設定されています。標準のオンライン インストールを続行するには、ユーザー名とパスワードを入力してください。プロキシ サーバーの資格情報については、システム管理者にお問い合わせください。',

        onlineWorkflowButton: '標準インストールを行う',
        downloadOnlyWorkflowButton: 'インストールせずにダウンロードする',
        fikWorkflowButton: 'ファイル インストール キーを持っている',
        licenseManagerWorkflowButton: 'ネットワーク ライセンス マネージャーをインストールする',

        AKToolTipHelpWithAssociation: 'アクティベーション キーは別のライセンスにリンクします。アクティベーション キーはライセンス管理者から入手できます。',
        AKToolTipHelpNoAssociation: 'アクティベーション キーはライセンスにリンクします。アクティベーション キーはライセンス管理者から入手できます。',
        downloadOnlyToolTipHelp: '製品を今すぐインストールせずにダウンロードして、後で 1 台以上のコンピューターにインストールできるようにします。',
        selectLicenseFileForLMToolTipHelp: 'MathWorks ライセンス センターから、ご使用のサーバー用のライセンス ファイルを生成します。',
        selectLicenseFileForToolTipHelp: 'MathWorks ライセンス センターまたはライセンス管理者からライセンス ファイルを取得してください。',
        licenseManagerToolTipHelp: 'このワークフローはライセンス管理者専用です。コンカレント ライセンスとネットワーク ネームド ユーザー ライセンスについては、ネットワーク ライセンス マネージャーをサーバーにインストールする必要があります。',
        akLabel: 'アクティベーション キーを入力する',
        installationFolderLabel: '保存先フォルダーの選択',
        downloadFolderLabel: '保存先フォルダーの選択',
        platformSelectionLabel: 'ターゲット プラットフォームの選択',
        browseButtonLabel: '参照',
        restoreDefault: '既定値に戻す',
        productTableLabel: '製品の選択',
        productTableLabelMinimal: '製品の選択 (推奨される製品があらかじめ選択されています)',
        productColumnHeader: 'すべて選択',
        advancedOptionText: '詳細オプション',
        optionsTitle: 'オプションの選択',
        shortcutLabel: 'デスクトップにショートカットを追加',
        symbolicLinkLabel: 'MATLAB スクリプトへのシンボリック リンクの作成:',
        userExperienceLabel: 'MATLAB の品質向上のため、ユーザー エクスペリエンス情報を MathWorks に送付する',
        finalLabel: 'インストールの完了',
        finalLabelDownloadOnly: 'ダウンロードの完了',
        fikNavTitle: 'ファイル インストール キー',
        folderSelectionNavTitle: 'インストール フォルダー',
        productSelectionNavTitle: '製品',
        optionsNavTitle: 'オプション',
        confirmationNavTitle: '確認',
        licenseSelectionTitle: 'ライセンス ファイルの選択',
        licenseSelectionFolderLabel: '(ライセンス ファイルの絶対パスを、ファイル名を含めて入力してください)',
        entitlementPanelTitle: 'ライセンスの選択',
        activationPanelTitle: 'アクティベーション キーの入力',
        activationPanelTitleA2AK: 'ライセンスのアクティベーション キーの入力',
        A2AKPanelContextHelp: 'このライセンスにアクセスするためにはアクティベーション キーが必要です。アクティベーション キーはライセンス管理者から入手できます。',
        entitlementTableTitle: 'ライセンス:',
        entitlementTableLicenseCol: 'ライセンス',
        entitlementTableLabelCol: 'ラベル',
        entitlementTableOptionCol: 'ライセンスの使用とオプション',
        activationKeyTitle: 'アクティベーション キーの入力:',
        activationModePanelTitle: '認証オプションの選択',
        activationModeRadioLabel: '今すぐこのコンピューターを承認',
        activationModeRadioText: 'ソフトウェアのアクティベーションを行います。インターネット接続は不要です。',
        activationModeAuthRadioLabel: 'ソフトウェアが起動するたびに認証 (サインイン)',
        activationModeAuthRadioText: 'インターネット接続が必要です。',
        configureService: 'サービスとして構成',
        configureServiceText: 'Windows システムでは、インストーラーによって、システムの起動時にライセンス マネージャーが自動的に起動するように構成されます。この既定の構成を受け入れた場合、ライセンス マネージャーを起動する最も簡単な方法は、ライセンス マネージャーをインストールしたコンピューターを再起動することです。',
        confirmUserTitle: 'ユーザーの確認',
        confirmUserNameLabel: '名前',
        confirmUserEmailLabel: '電子メール',
        confirmWinUserNameLabel: 'Windows のユーザー名',
        editWinUserNameLabel: '編集',
        ConfirmLinuxUserName: 'glnxa64 のログイン名',
        ConfirmMacUserName: 'maci のログイン名',
        linuxOrMacUserNameLabel: 'ログイン名',
        firstName: '名',
        lastName: '姓',
        getUserInfoBtnLabel: '私がソフトウェアを使用します',
        openDownloadFolder: 'ダウンロード フォルダーを開く',
        activateMATLAB: 'ソフトウェアのアクティベーションを行う',
        activateNote: 'メモ: ソフトウェアを使用するには、まずアクティベーションを行わなければなりません。',
        provideUserInfoTitle: 'ユーザー情報の提供',
        provideUserInfoText: 'このライセンスは 1 人しか使用できません。ライセンスをもつエンド ユーザーを指定してください:',
        provideUserInfo: '(必要に応じてこのユーザーの MathWorks アカウントが作成されます)。',
        productDependecyDialogTitle: '製品の依存関係',
        productDependecyDialogAddBtnLabel: '追加',
        productDependecyDialogDoNotAddBtnLabel: "追加しない",
        productDependecyDialogCancelBtnLabel: 'キャンセル',
        student: 'はい、私は学生です',
        notStudent: 'いいえ、私は学生ではありません',
        studentConfirmTitle: 'Student Version 使用ポリシー',
        studentConfirmMessage: 'これは学生向けライセンスです。このライセンスを利用するには学位を授与する高等教育機関に在学している学生か高校生または教師でなければなりません。商用その他の目的には使用できません。このライセンスは学生コミュニティへ特別に提供されており、ライセンス使用条件に則って使用するようご協力をお願いします。\n\nあなたは学生で、学位を授与する機関で実施される課程に関連してこのソフトウェアを使用しますか?\n\n',
        yes: 'はい',
        no: 'いいえ',
        userNameModifyTitle: 'Windows のユーザー名の警告',
        userNameModifyMessage1: 'ソフトウェアが次の名前以外のユーザー名で実行される場合にのみ変更してください: ${0}',
        userNameModifyMessage2: ' \n \nユーザー名の詳細については、こちらの <a href="https://www.mathworks.com/pi_unc_mpi_${0}_${1}" target=\"_blank\">MATLAB Answer</a> を参照してください。',
        loginNameModifyTitle: 'ログイン名の警告',
        loginNameModifyMessage1: 'ソフトウェアが次の名前以外のログイン名で実行される場合にのみ変更してください: ${0}',
        loginNameModifyMessage2: '\n \nログイン名の詳細については、こちらの <a href="https://www.mathworks.com/pi_unc_mpi_${0}_${1}" target=\"_blank\">MATLAB Answer</a> を参照してください',
        userNameRequired: 'ユーザー名が必要です',
        confirmationDialogTitle: 'インストールの中止',
        confirmationDialogText: 'ここで終了すると、インストールを最初からやり直さなければなりません。<br><br>終了しますか?',
        mySelectionButton: '選択項目を使用',
        recommendedSelectionButton: '推奨項目を使用',
        radioButtonDescriptionForLicenseAgreement: 'ライセンス許諾の条件に同意しますか?',
        radioButtonsYesText: 'はい',
        radioButtonsNoText: 'いいえ',
        signInButtonText: 'サインイン',
        connectionErrorTitle: '接続エラー',
        connectionErrorMsg: 'アプリケーションは MathWorks に接続できませんでした。<br>この問題を解決するには、<a href="http://www.mathworks.com/pi_dlerr_mpi " target="_blank">カスタマー サポート</a>にお問い合わせください',
        confirmationPanelTitle: '選択の確認',
        confirmDestinationFolderLabel: 'インストール先',
        confirmPlatformsLabel: 'プラットフォーム',
        confirmProductsLabel: '製品',
        confirmLicensingLabel: 'ライセンス',
        installationNotesTitle: '<b>このインストールではさらに設定が必要となる場合があります。</b><br><br>',
        licensingNavTitle: 'ライセンス',
        destinationNavTitle: 'インストール先',
        platformsNavTitle: 'プラットフォーム',
        genericErrorTitle: '予期せぬ問題が発生しました。',
        genericErrorMessage: 'この問題を解決するには、<a href="https://www.mathworks.com/support" target="_blank">テクニカル サポート</a>にお問い合わせください',
        closeButtonLabel: '閉じる',
        mathworksTrademarksText: 'MATLAB and Simulink are registered trademarks of The MathWorks, Inc.Please see mathworks.com/trademarks for a list of additional trademarks.Other product or brand names may be trademarks or registered trademarks of their respective holders.',
        mathworksPatentsText: 'MathWorks products are protected by patents (see mathworks.com/patents) and copyright laws.Any unauthorized use, reproduction, or distribution may result in civil and criminal penalties.',
        symbolicLinkFolderLabel: 'シンボリック リンク フォルダーを選択',
        noArchiveErrorMsg: 'インストール用の製品ファイルが見つかりません。ヘルプについては、こちらの <a href="http://www.mathworks.com/pi_miferr_mpi " target="_blank">MATLAB Answer</a> を参照してください。',
        noArchiveErrorTitle: 'インストール ファイルの不足',
        noInternetNoArchiveErrorMsg1: '問題は、次のいずれかである可能性があります。',
        noInternetNoArchiveErrorMsg2: '<li>インストーラーが MathWorks に接続できません。ファイアウォールまたはウイルス対策ソフトウェアが原因である可能性があります。詳細については、こちらの <a href="http://www.mathworks.com/pi_icerr_mpi " target="_blank">MATLAB Answer</a> を参照してください。</li>',
        noInternetNoArchiveErrorMsg3: '<li>オフラインのインストールに必要な製品ファイルが見つかりません。詳細については、こちらの <a href="http://www.mathworks.com/pi_miferr_mpi " target="_blank">MATLAB Answer</a> を参照してください。</li>',
        noInternetNoArchiveErrorTitle: '続行できません'
    });
