/* Copyright 2020-2021 The MathWorks, Inc. */
define({
    
        dialogTitle: 'Instalador de Matlab',
        installButtonLabel: 'Comenzar instalación',
        downloadButtonLabel: 'Comenzar descarga',
        forwardButtonLabel: 'Siguiente',
        cancelButtonLabel: 'Cancelar',
        finishButtonLabel: 'Cerrar',
        guiltForwardButtonLabel: 'Soy estudiante',
        closeLabel: 'Aceptar',
        continueLabel: 'Continuar',
        ignoreLabel: 'Ignorar',
        licenseAgreementTitle: 'Acuerdo de licencia de MathWorks',
        patentsAndTrademarksTitle: 'Derechos de autor, marcas comerciales y patentes',
        fikWorkflowLabel: 'Instalar con la clave de instalación de archivos',
        proxyTitle: 'Autenticación de proxy',
        proxyUser: 'ID de usuario del servidor proxy:',
        proxyPassword: 'Contraseña del servidor proxy:',
        downloadOnlyWorkflowLabel: 'Descargar sin instalar',
        licenseManagerWorkflowLabel: 'Instalación del administrador de licencia de red',
        fikLabel: 'Introducir clave de instalación de archivos',
        fikContextHelp: 'Una clave de instalación de archivos identifica los productos que puede instalar y le permite instalarlos sin una conexión a Internet.  También debe tener su archivo de licencia para este flujo de trabajo. Puede conseguir una clave de instalación de archivos y un archivo de licencia del Centro de licencias de Mathworks o del administrador de su licencia.',
        downloadFolderContextHelp: 'Descargue productos sin instalación para poder instalarlos en uno o más ordenadores más adelante.',
        activationKeyContextHelp: 'Una clave de activación le vincula con otra licencia. Puede conseguir una clave de activación de su administrador de licencias.',
        proxyContextHelp: 'Su equipo se ha configurado para utilizar un servidor proxy para obtener acceso a Internet. Introduzca el nombre de usuario y la contraseña para continuar con una instalación online estándar. Póngase en contacto con su administrador del sistema para obtener las credenciales del servidor proxy.',

        onlineWorkflowButton: 'Quiero realizar una instalación estándar',
        downloadOnlyWorkflowButton: 'Quiero descargar sin instalar',
        fikWorkflowButton: 'Tengo una clave de instalación de archivos',
        licenseManagerWorkflowButton: 'Quiero instalar un administrador de licencias de red',

        AKToolTipHelpWithAssociation: 'Una clave de activación le vincula con otra licencia. Puede conseguir una clave de activación de su administrador de licencias.',
        AKToolTipHelpNoAssociation: 'Una clave de activación le vincula con una licencia. Puede conseguir una clave de activación de su administrador de licencias.',
        downloadOnlyToolTipHelp: 'Descargue productos sin instalación para poder instalarlos en uno o más ordenadores más adelante.',
        selectLicenseFileForLMToolTipHelp: 'Genere un archivo de licencia para su servidor desde el Centro de licencias de MathWorks.',
        selectLicenseFileForToolTipHelp: 'Obtenga el archivo de licencia del Centro de licencias de MathWorks o del administrador de su licencia.',
        licenseManagerToolTipHelp: 'Este flujo de trabajo es solo para administradores de licencias. Necesita instalar el administrador de licencias de red en un servidor para las licencias concurrentes y de usuario designado de red.',
        akLabel: 'Introduzca una clave de activación',
        installationFolderLabel: 'Seleccione una carpeta de destino',
        downloadFolderLabel: 'Seleccione una carpeta de destino',
        platformSelectionLabel: 'Seleccione las plataformas objetivo',
        browseButtonLabel: 'Examinar',
        restoreDefault: 'Restaurar valores predeterminados',
        productTableLabel: 'Seleccionar productos',
        productTableLabelMinimal: 'Seleccionar productos (los productos recomendados se seleccionan previamente)',
        productColumnHeader: 'Seleccionar todos',
        advancedOptionText: 'Opciones avanzadas',
        optionsTitle: 'Seleccionar opciones',
        shortcutLabel: 'Agregar atajo al escritorio',
        symbolicLinkLabel: 'Cree enlaces simbólicos a scripts en:',
        userExperienceLabel: 'Mejore MATLAB enviando información de experiencia del usuario a MathWorks',
        finalLabel: 'Instalación completada',
        finalLabelDownloadOnly: 'Descarga completada',
        fikNavTitle: 'Clave de instalación de archivos',
        folderSelectionNavTitle: 'Carpeta de instalación',
        productSelectionNavTitle: 'Productos',
        optionsNavTitle: 'Opciones',
        confirmationNavTitle: 'Confirmación',
        licenseSelectionTitle: 'Seleccionar archivo de licencia',
        licenseSelectionFolderLabel: '(introduzca la ruta completa de su archivo de licencia, incluido el nombre del archivo)',
        entitlementPanelTitle: 'Seleccionar licencia',
        activationPanelTitle: 'Introduzca la clave de activación',
        activationPanelTitleA2AK: 'Introduzca la clave de activación para su licencia',
        A2AKPanelContextHelp: 'Se requiere una clave de activación para acceder a esta licencia. Puede conseguir una clave de activación de su administrador de licencias.',
        entitlementTableTitle: 'Licencias:',
        entitlementTableLicenseCol: 'Licencia',
        entitlementTableLabelCol: 'Etiqueta',
        entitlementTableOptionCol: 'Opción y uso de la licencia',
        activationKeyTitle: 'Introduzca la clave de activación:',
        activationModePanelTitle: 'Seleccione una opción de autenticación',
        activationModeRadioLabel: 'Autorizar a este ordenador ahora',
        activationModeRadioText: 'Activar el software para este ordenador. No se necesita conexión a Internet para ejecutar el software.',
        activationModeAuthRadioLabel: 'Autenticar (iniciar sesión) cada vez que se inicia el software',
        activationModeAuthRadioText: 'Se necesita conexión a Internet para ejecutar el software.',
        configureService: 'Configurar como servicio',
        configureServiceText: 'En los sistemas Windows, el instalador configura el administrador de licencias para que se inicie de forma automática cuando se inicie el sistema. Si acepta esta configuración predeterminada, la manera más fácil de iniciar el administrador de licencias es volver a iniciar el ordenador en el que instaló el administrador de licencias.',
        confirmUserTitle: 'Confirmar usuario',
        confirmUserNameLabel: 'Nombre',
        confirmUserEmailLabel: 'Correo electrónico',
        confirmWinUserNameLabel: 'Nombre de usuario de Windows',
        editWinUserNameLabel: 'editar',
        ConfirmLinuxUserName: 'Nombre de inicio de sesión para glnxa64',
        ConfirmMacUserName: 'Nombre de inicio de sesión para maci',
        linuxOrMacUserNameLabel: 'Nombre de inicio de sesión',
        firstName: 'Nombre',
        lastName: 'Apellido',
        getUserInfoBtnLabel: 'Utilizaré este software',
        openDownloadFolder: 'Abrir carpeta Descargas',
        activateMATLAB: 'Active su software',
        activateNote: 'Nota: Para utilizar el software, debe activarlo primero.',
        provideUserInfoTitle: 'Proporcionar información del usuario',
        provideUserInfoText: 'Solo una persona puede utilizar esta licencia. Especifique el usuario final con licencia:',
        provideUserInfo: '(si es necesario se creará una cuenta de MathWorks para esta persona).',
        productDependecyDialogTitle: 'Dependencias del producto',
        productDependecyDialogAddBtnLabel: 'Agregar',
        productDependecyDialogDoNotAddBtnLabel: "No agregar",
        productDependecyDialogCancelBtnLabel: 'Cancelar',
        student: 'Sí, soy estudiante',
        notStudent: 'No, no soy estudiante',
        studentConfirmTitle: 'Política de uso de estudiantes',
        studentConfirmMessage: 'Esta es una Licencia de estudiante. Debe ser un/una estudiante matriculado/matriculada en una institución de enseñanza superior que otorgue titulaciones o estudiante o docente en un instituto/escuela preuniversitaria. No es para uso comercial ni de otro tipo. MathWorks ofrece esta licencia como un servicio especial a los estudiantes y pide ayuda para que no se abuse de sus términos.\n\n¿Es estudiante y utiliza el software para los trabajos de curso en una escuela, colegio o universidad?\n\n',
        yes: 'Sí',
        no: 'No',
        userNameModifyTitle: 'Advertencia del nombre de usuario de Windows',
        userNameModifyMessage1: 'Cambiar SOLO si el software se va a ejecutar con un nombre de usuario diferente de: ${0}',
        userNameModifyMessage2: ' \n \nPara obtener más información sobre nombres de usuario, consulte esta <a href="https://www.mathworks.com/pi_unc_mpi_${0}_${1}" target=\"_blank\">respuesta de MATLAB</a>.',
        loginNameModifyTitle: 'Advertencia de nombre de inicio de sesión',
        loginNameModifyMessage1: 'Cambiar SOLO si el software se va a ejecutar con un nombre de inicio de sesión diferente de: ${0}',
        loginNameModifyMessage2: '\n \nPara obtener más información sobre nombres de inicio de sesión, consulte esta <a href="https://www.mathworks.com/pi_unc_mpi_${0}_${1}" target=\"_blank\">respuesta de MATLAB</a>.',
        userNameRequired: 'El nombre de usuario es obligatorio',
        confirmationDialogTitle: 'Abandonar instalador',
        confirmationDialogText: 'Si abandona en este instante, debe reiniciar la instalación desde el principio.<br><br>¿Seguro que desea abandonar ahora?',
        mySelectionButton: 'Utilizar mi selección',
        recommendedSelectionButton: 'Utilizar recomendación',
        radioButtonDescriptionForLicenseAgreement: '¿Acepta los términos del acuerdo de licencia?',
        radioButtonsYesText: 'Sí',
        radioButtonsNoText: 'No',
        signInButtonText: 'Iniciar sesión',
        connectionErrorTitle: 'Error de conexión',
        connectionErrorMsg: 'La aplicación no se pudo conectar a MathWorks.<br>Para resolver este problema, póngase en contacto con el <a href="http://www.mathworks.com/pi_dlerr_mpi " target="_blank">servicio de atención al cliente</a>.',
        confirmationPanelTitle: 'Confirmar selecciones',
        confirmDestinationFolderLabel: 'DESTINO',
        confirmPlatformsLabel: 'PLATAFORMAS',
        confirmProductsLabel: 'PRODUCTOS',
        confirmLicensingLabel: 'LICENCIAS',
        installationNotesTitle: '<b>Puede que su instalación necesite pasos de configuración adicionales.</b><br><br>',
        licensingNavTitle: 'Licencias',
        destinationNavTitle: 'Destino',
        platformsNavTitle: 'PLATAFORMAS',
        genericErrorTitle: 'Ocurrió algo inesperado.',
        genericErrorMessage: 'Para resolver este problema, póngase en contacto con el <a href="https://www.mathworks.com/support" target="_blank">soporte técnico</a>.',
        closeButtonLabel: 'Cerrar',
        mathworksTrademarksText: 'MATLAB and Simulink are registered trademarks of The MathWorks, Inc. Please see mathworks.com/trademarks for a list of additional trademarks. Other product or brand names may be trademarks or registered trademarks of their respective holders.',
        mathworksPatentsText: 'Los productos de MathWorks están protegidos por patentes (consulte mathworks.com/patents) y leyes de derechos de autor. Cualquier uso, reproducción o distribución no autorizada puede resultar en sanciones civiles y penales.',
        symbolicLinkFolderLabel: 'Seleccione la carpeta del vínculo simbólico',
        noArchiveErrorMsg: 'No se pudieron encontrar los archivos de producto para la instalación. Para obtener ayuda, consulte esta <a href="http://www.mathworks.com/pi_miferr_mpi " target="_blank">respuesta de MATLAB</a>.',
        noArchiveErrorTitle: 'Archivos de instalación faltantes',
        noInternetNoArchiveErrorMsg1: 'Es posible que el problema sea uno de los siguientes:',
        noInternetNoArchiveErrorMsg2: '<li>El instalador no se pudo conectar con MathWorks. Esto puede deberse a un cortafuegos o un software de antivirus.  Para obtener más información, consulte esta <a href="http://www.mathworks.com/pi_icerr_mpi " target="_blank">respuesta de MATLAB</a>.</li>',
        noInternetNoArchiveErrorMsg3: '<li>Faltan los archivos de producto necesarios para la instalación sin conexión. Para obtener más información, consulte esta <a href="http://www.mathworks.com/pi_miferr_mpi " target="_blank">respuesta de MATLAB</a>.</li>',
        noInternetNoArchiveErrorTitle: 'No se pudo continuar'
    });
