/* Copyright 2020-2021 The MathWorks, Inc. */
define({
    
        dialogTitle: 'Matlab 安装程序',
        installButtonLabel: '开始安装',
        downloadButtonLabel: '开始下载',
        forwardButtonLabel: '下一步',
        cancelButtonLabel: '取消',
        finishButtonLabel: '关闭',
        guiltForwardButtonLabel: '我是学生',
        closeLabel: '确定',
        continueLabel: '继续',
        ignoreLabel: '忽略',
        licenseAgreementTitle: 'MathWorks 许可协议',
        patentsAndTrademarksTitle: '版权、商标和专利',
        fikWorkflowLabel: '使用文件安装密钥进行安装',
        proxyTitle: '代理身份验证',
        proxyUser: '代理服务器用户 ID:',
        proxyPassword: '代理服务器密码:',
        downloadOnlyWorkflowLabel: '下载而不安装',
        licenseManagerWorkflowLabel: '网络许可证管理器安装',
        fikLabel: '输入文件安装密钥',
        fikContextHelp: '文件安装密钥会确认您可以安装的产品，并允许您在没有 Internet 连接的情况下安装它们。您还必须拥有此工作流所需的许可证文件。您可以从 MathWorks 许可证中心或您的许可证管理员处获得文件安装密钥和许可证文件。',
        downloadFolderContextHelp: '下载产品但不立即安装，以便稍后在一台或多台计算机上安装。',
        activationKeyContextHelp: '使用激活密钥关联到另一个许可证。您可以从许可证管理员处获得激活密钥。',
        proxyContextHelp: '您的计算机已配置为使用代理服务器访问 Internet。输入用户名和密码以继续标准在线安装。请联系系统管理员以获取代理服务器凭据。',

        onlineWorkflowButton: '我要进行标准安装',
        downloadOnlyWorkflowButton: '我要下载但不安装',
        fikWorkflowButton: '我有文件安装密钥',
        licenseManagerWorkflowButton: '我要安装网络许可证管理器',

        AKToolTipHelpWithAssociation: '使用激活密钥关联到另一个许可证。您可以从许可证管理员处获得激活密钥。',
        AKToolTipHelpNoAssociation: '使用激活密钥关联到一个许可证。您可以从许可证管理员处获得激活密钥。',
        downloadOnlyToolTipHelp: '下载产品但不立即安装，以便稍后在一台或多台计算机上安装。',
        selectLicenseFileForLMToolTipHelp: '从 MathWorks 许可证中心为您的服务器生成许可证文件。',
        selectLicenseFileForToolTipHelp: '从 MathWorks 许可证中心或您的许可证管理员处获取许可证文件。',
        licenseManagerToolTipHelp: '此工作流仅适用于许可证管理员。对于并发许可证和网络指定用户许可证，您需要在服务器上安装网络许可证管理器。',
        akLabel: '输入激活密钥',
        installationFolderLabel: '选择目标文件夹',
        downloadFolderLabel: '选择目标文件夹',
        platformSelectionLabel: '选择目标平台',
        browseButtonLabel: '浏览',
        restoreDefault: '还原默认值',
        productTableLabel: '选择产品',
        productTableLabelMinimal: '选择产品(推荐的产品已预先选择)',
        productColumnHeader: '全选',
        advancedOptionText: '高级选项',
        optionsTitle: '选择选项',
        shortcutLabel: '将快捷方式添加到桌面',
        symbolicLinkLabel: '创建指向以下位置中的 MATLAB 脚本的符号链接:',
        userExperienceLabel: '通过向 MathWorks 公司发送用户体验信息来帮助改进 MATLAB',
        finalLabel: '安装完毕',
        finalLabelDownloadOnly: '下载完毕',
        fikNavTitle: '文件安装密钥',
        folderSelectionNavTitle: '安装文件夹',
        productSelectionNavTitle: '产品',
        optionsNavTitle: '选项',
        confirmationNavTitle: '确认',
        licenseSelectionTitle: '选择许可证文件',
        licenseSelectionFolderLabel: '(输入许可证文件的完整路径，包括文件名)',
        entitlementPanelTitle: '选择许可证',
        activationPanelTitle: '输入激活密钥',
        activationPanelTitleA2AK: '输入许可证的激活密钥',
        A2AKPanelContextHelp: '访问此许可证需要激活密钥。您可以从许可证管理员处获得激活密钥。',
        entitlementTableTitle: '许可证:',
        entitlementTableLicenseCol: '许可证',
        entitlementTableLabelCol: '标签',
        entitlementTableOptionCol: '许可证用途和选项',
        activationKeyTitle: '输入激活密钥:',
        activationModePanelTitle: '选择身份验证选项',
        activationModeRadioLabel: '立即授权此计算机',
        activationModeRadioText: '在此计算机上激活本软件运行软件时不需要 Internet 连接。',
        activationModeAuthRadioLabel: '每次启动软件时都需要身份验证(登录)',
        activationModeAuthRadioText: '运行软件时需要 Internet 连接。',
        configureService: '配置为服务',
        configureServiceText: '在 Windows 系统上，安装程序会将许可证管理器配置为在启动系统时自动启动。如果您接受此默认配置，则启动许可证管理器的最简便方法就是重新启动安装了许可证管理器的计算机。',
        confirmUserTitle: '确认用户',
        confirmUserNameLabel: '名称',
        confirmUserEmailLabel: '电子邮件',
        confirmWinUserNameLabel: 'Windows 用户名',
        editWinUserNameLabel: '编辑',
        ConfirmLinuxUserName: 'glnxa64 的登录名',
        ConfirmMacUserName: 'maci 的登录名',
        linuxOrMacUserNameLabel: '登录名',
        firstName: '名字',
        lastName: '姓氏',
        getUserInfoBtnLabel: '我将使用本软件',
        openDownloadFolder: '打开 "下载" 文件夹',
        activateMATLAB: '激活您的软件',
        activateNote: '注意: 要使用该软件，必须先激活它。',
        provideUserInfoTitle: '提供用户信息',
        provideUserInfoText: '只有一个人可以使用此许可证。指定最终许可用户:',
        provideUserInfo: '(如有必要，为该用户创建 MathWorks 帐户。)',
        productDependecyDialogTitle: '产品依赖项',
        productDependecyDialogAddBtnLabel: '添加',
        productDependecyDialogDoNotAddBtnLabel: "不添加",
        productDependecyDialogCancelBtnLabel: '取消',
        student: '是，我是学生',
        notStudent: '不，我不是学生',
        studentConfirmTitle: '学生使用政策',
        studentConfirmMessage: '这是学生许可证。您必须是授予学位的高等教育机构在籍的学生，或中学/大学预科学校的学生。该许可证不能用于商业或其他用途。MathWorks 将此许可证作为一项特殊服务提供给学生，并需要您帮助我们杜绝软件滥用。\n\n您是为了完成功课而使用本软件的在校学生吗?\n\n',
        yes: '是',
        no: '否',
        userNameModifyTitle: 'Windows 用户名警告',
        userNameModifyMessage1: '仅当要使用不同于以下所示的用户名运行软件时，才进行更改: ${0}',
        userNameModifyMessage2: ' \n \n有关用户名的详细信息，请参阅相应的 <a href="https://www.mathworks.com/pi_unc_mpi_${0}_${1}" target=\"_blank\">MATLAB Answer</a>。',
        loginNameModifyTitle: '登录名警告',
        loginNameModifyMessage1: '仅当要使用不同于以下所示的登录名运行软件时，才进行更改: ${0}',
        loginNameModifyMessage2: '\n \n有关登录名的详细信息，请参阅相应的 <a href="https://www.mathworks.com/pi_unc_mpi_${0}_${1}" target=\"_blank\">MATLAB Answer</a>',
        userNameRequired: '用户名为必填项',
        confirmationDialogTitle: '退出安装程序',
        confirmationDialogText: '如果现在退出，您必须从头开始重新启动安装。<br><br>是否确实要现在退出?',
        mySelectionButton: '使用我选择的内容',
        recommendedSelectionButton: '使用推荐内容',
        radioButtonDescriptionForLicenseAgreement: '是否接受许可协议的条款?',
        radioButtonsYesText: '是',
        radioButtonsNoText: '否',
        signInButtonText: '登录',
        connectionErrorTitle: '连接错误',
        connectionErrorMsg: '应用程序无法连接到 MathWorks。<br>要解决此问题，请联系<a href="http://www.mathworks.com/pi_dlerr_mpi " target="_blank">客户支持</a>',
        confirmationPanelTitle: '确认选择',
        confirmDestinationFolderLabel: '目标',
        confirmPlatformsLabel: '平台',
        confirmProductsLabel: '产品',
        confirmLicensingLabel: '许可',
        installationNotesTitle: '<b>您的安装可能需要额外的配置步骤。</b><br><br>',
        licensingNavTitle: '许可',
        destinationNavTitle: '目标',
        platformsNavTitle: '平台',
        genericErrorTitle: '出现了异常情况。',
        genericErrorMessage: '要解决此问题，请联系<a href="https://www.mathworks.com/support" target="_blank">技术支持</a>',
        closeButtonLabel: '关闭',
        mathworksTrademarksText: 'MATLAB and Simulink are registered trademarks of The MathWorks, Inc.Please see mathworks.com/trademarks for a list of additional trademarks.Other product or brand names may be trademarks or registered trademarks of their respective holders.',
        mathworksPatentsText: 'MathWorks products are protected by patents (see mathworks.com/patents) and copyright laws.Any unauthorized use, reproduction, or distribution may result in civil and criminal penalties.',
        symbolicLinkFolderLabel: '选择符号链接文件夹',
        noArchiveErrorMsg: '找不到安装的产品文件。有关帮助，请参阅相应的 <a href="http://www.mathworks.com/pi_miferr_mpi " target="_blank">MATLAB Answer</a>。',
        noArchiveErrorTitle: '缺少安装文件',
        noInternetNoArchiveErrorMsg1: '问题可能是以下项之一:',
        noInternetNoArchiveErrorMsg2: '<li>安装程序无法连接到 MathWorks。这可能是防火墙或防病毒软件导致的。有关详细信息，请参阅相应的 <a href="http://www.mathworks.com/pi_icerr_mpi " target="_blank">MATLAB Answer</a>。</li>',
        noInternetNoArchiveErrorMsg3: '<li>离线安装所需的产品文件缺失。有关详细信息，请参阅相应的 <a href="http://www.mathworks.com/pi_miferr_mpi " target="_blank">MATLAB Answer</a>。</li>',
        noInternetNoArchiveErrorTitle: '无法继续'
    });
